/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DateChangedEvent, EventClickedEvent, ICalendarOptions, IDateFooter, IHoliday, MoreEventsClickedEvent } from "./models";
import { IEvent } from "./models/event.model";
export { DateChangedEvent, EventClickedEvent, ICalendarOptions, IDateFooter, IHoliday, MoreEventsClickedEvent } from "./models";
export { IEvent } from "./models/event.model";
export namespace Components {
    interface TeCalendarFull {
        "currentMonth": Date;
        "dateFooters": IDateFooter[];
        "events": IEvent[];
        "holidays": IHoliday[];
        "options": ICalendarOptions;
    }
}
export interface TeCalendarFullCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTeCalendarFullElement;
}
declare global {
    interface HTMLTeCalendarFullElement extends Components.TeCalendarFull, HTMLStencilElement {
    }
    var HTMLTeCalendarFullElement: {
        prototype: HTMLTeCalendarFullElement;
        new (): HTMLTeCalendarFullElement;
    };
    interface HTMLElementTagNameMap {
        "te-calendar-full": HTMLTeCalendarFullElement;
    }
}
declare namespace LocalJSX {
    interface TeCalendarFull {
        "currentMonth"?: Date;
        "dateFooters"?: IDateFooter[];
        "events"?: IEvent[];
        "holidays"?: IHoliday[];
        "onDateSelected"?: (event: TeCalendarFullCustomEvent<DateChangedEvent>) => void;
        "onEventSelected"?: (event: TeCalendarFullCustomEvent<EventClickedEvent>) => void;
        "onMoreEventsClicked"?: (event: TeCalendarFullCustomEvent<MoreEventsClickedEvent>) => void;
        "options"?: ICalendarOptions;
    }
    interface IntrinsicElements {
        "te-calendar-full": TeCalendarFull;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "te-calendar-full": LocalJSX.TeCalendarFull & JSXBase.HTMLAttributes<HTMLTeCalendarFullElement>;
        }
    }
}
